version: "3.8"
services:
  api:
    environment:
      - THORN_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - THORN_API_HOST=0.0.0.0
      - THORN_API_PORT=3001
      - THORN_ADMIN_USERNAME=admin
      - THORN_ADMIN_PASSWORD=admin
      - THORN_ENCRYPTION_KEY=#.9U#JW#XbB12345
      - THORN_ENCRYPTION_SECRET=abc&1*~#^2^#s0^=)^^7%b34
      - THORN_SIGNING_KEY=secret
      - THORN_DEV_MODE=true
      - THORN_LOG_LEVEL=debug
      - THORN_LOG_SINK=stdout
      - THORN_LOG_FORMAT=text
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    entrypoint: ["air", ".", "-c", "./.air.toml"]
    ports:
      - 3001:3001
    depends_on:
      - postgres
    volumes:
      - "./:/app"
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  data:
    driver: local
