version: "3.8"
services:
  keydb:
    image: eqalpha/keydb:x86_64_v6.3.3
    container_name: keydb
    command: keydb-server --server-threads 4 --protected-mode no --appendonly yes
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - ./keydb/redis.conf:/etc/keydb/redis.conf
      - ./keydb/data:/data
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      - KEYDB_CONN_STRING=keydb:6379
      - VAULT_DB_HOST=keydb
      - VAULT_DB_PORT=6379
      - VAULT_DB_USER=default
      - VAULT_DB_PASSWORD=
    working_dir: /code
    depends_on:
      - keydb
    command: sh -c "cd vault && go test && cd .. && cd api && go test && cd .."
    volumes:
      - "./:/code"

volumes:
  data:
    driver: local
