version: "3.8"
services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  api:
    profiles: ["simulations"]
    environment:
      - THORN_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - THORN_API_HOST=0.0.0.0
      - THORN_API_PORT=3001
      - THORN_ADMIN_USERNAME=admin
      - THORN_ADMIN_PASSWORD=admin
      - THORN_ENCRYPTION_KEY=#.9U#JW#XbB12345
      - THORN_ENCRYPTION_SECRET=abc&1*~#^2^#s0^=)^^7%b34
      - THORN_SIGNING_KEY=secret
      - THORN_DEV_MODE=true
      - THORN_LOG_LEVEL=info
      - THORN_LOG_SINK=none
      - THORN_LOG_FORMAT=text
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    entrypoint: ["/go/bin/api"]
    ports:
      - 3001:3001
    depends_on:
      - postgres
    volumes:
      - "./:/app"
  simulations:
    profiles: ["simulations"]
    build:
      context: .
      dockerfile: Dockerfile
      target: simulator
    environment:
      - THORN_URL=http://api:3001
    working_dir: /code
    depends_on:
      - api
      - postgres
    command: sh -c "cd simulator && ./simulate.sh"
    volumes:
      - "./:/code"
  tests:
    profiles: ["tests"]
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - THORN_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - THORN_ADMIN_USERNAME=admin
      - THORN_ADMIN_PASSWORD=admin
      - THORN_ENCRYPTION_KEY=#.9U#JW#XbB12345
      - THORN_ENCRYPTION_SECRET=abc&1*~#^2^#s0^=)^^7%b34
      - THORN_SIGNING_KEY=secret
    working_dir: /code
    depends_on:
      - postgres
    command: sh -c "go test ./vault && go test ./api"
    volumes:
      - "./:/code"
