[db]
host = "localhost"
port = 6379
user = "default"
password = ""
db = 0

[system]
env_prefix = "VAULT_"
dev_mode = true

[api]
host = "localhost"
port = 3000

[api.jwt]
secret = "secret"
ttl = 3600000000000 # TODO: Not used right now but should be the default

[admin]
access_key = "admin"
access_secret = "admin"

[encryption]
key = "#.9U#JW#XbB12345"
secret = "abc&1*~#^2^#s0^=)^^7%b34"

[log]
output = "stdout"
level = "debug"
