[db]
host = "localhost"
port = 6379
user = "default"
password = ""
db = 0

[system]
env_prefix = "VAULT_"
dev_mode = true

[api]
host = "localhost"
port = 3001

[signing]
key = "secret"

[admin]
access_key = "admin"
access_secret = "admin"

[encryption]
key = "#.9U#JW#XbB12345"
secret = "abc&1*~#^2^#s0^=)^^7%b34"

[log]
handler = "text"
sink = "stdout"
level = "debug"
